- id: entrench
  name: entrench
  description: "Run 'entrench'"
  entry: entrench
  language: python
  types_or: [markdown]
  args: ["update"]
  pass_filenames: false
  additional_dependencies: []
  minimum_pre_commit_version: "2.9.2"
