exclude: "^(third_party|api/openapiv2|server/proto/proto|\\.vale/Microsoft|\\.idea)/.*$"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: file-contents-sorter
        files: "(^\\.vale/config/vocabularies/.*$|\\.gitignore)"
  - repo: https://github.com/timothycrosley/isort.git
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.1
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
